name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        heroku --version

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | heroku login --api-key

    - name: Check or Create Heroku App
      env:
        HEROKU_APP_NAME: my-python-app-${{ github.run_id }}
      run: |
        # Check if the app exists
        if heroku apps:info --app $HEROKU_APP_NAME > /dev/null 2>&1; then
          echo "Heroku app $HEROKU_APP_NAME already exists."
        else
          echo "Creating Heroku app $HEROKU_APP_NAME..."
          heroku create $HEROKU_APP_NAME
        fi
        # Set the Heroku remote for Git
        heroku git:remote -a $HEROKU_APP_NAME

    - name: Deploy to Heroku
      env:
        HEROKU_APP_NAME: my-python-app-${{ github.run_id }}
      run: |
        git push heroku main
