Run git push heroku main
  git push heroku main
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.13.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.3/x64/lib
    HEROKU_API_KEY: ***
    HEROKU_APP_NAME: my-python-app-15549297124
  
remote: 
remote: !	Push rejected, source repository is a shallow clone. Unshallow it with `git fetch --all --unshallow` and try pushing again.        
remote: 
To https://git.heroku.com/my-python-app-15549297124.git
 ! [remote rejected] main -> main (shallow update not allowed)
error: failed to push some refs to 'https://git.heroku.com/my-python-app-15549297124.git'
Error: Process completed with exit code 1
